name: Build

on:
  push:
    branches:
    - main
    tags:
    - v*.*.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DEPLOY_EMAIL: eah0592@gmail.com
  DEPLOY_PATH: erichaagdev/erichaag.dev/prod
  DEPLOY_REPOSITORY: erichaagdev/deployments

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,prefix=
          type=raw,value=latest
    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build & push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ env.DEPLOY_REPOSITORY }}
        token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
    - name: Deployment update
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$DEPLOY_EMAIL"
        VERSION=$(echo "$GITHUB_SHA" | cut -c -7)
        IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION"
        cd "$DEPLOY_PATH"
        kustomize edit set image "$IMAGE"
        git commit --all --message "Deploy $IMAGE"
        git push
